### ISSUE TITLE
Use bytes instead of char

### ISSUE THREAD

**Issue by Michael-F-Bryan** [Michael-F-Bryan/gcode-rs#17]
At the moment, the only reason the lexer wants a stream of `char` is because I use a lot of simple string-y methods (e.g. to_upper and is_digit). There are probably some pretty decent speed improvements to be had if we were to accept a stream of bytes instead. It also makes things more convenient when you're working with files and serial connections.

**Comment by luser** [comment]
FYI [`AsciiExt`](https://doc.rust-lang.org/std/ascii/trait.AsciiExt.html) should have everything you need to do this, but unfortunately some of the useful methods like `is_ascii_whitespace` [are currently unstable](https://github.com/rust-lang/rust/issues/39658).

**Comment by Michael-F-Bryan** [comment]
It looks like `AsciiExt` is part of `std`, while this really needs to be a `#![no_std]` library so it can be used on microcontrollers.

I've actually started the parsing part of this library to make it work on bytes directly, I just haven't had time to finish it off and land the PR.
