### ISSUE TITLE
Gcode::number using f32 is confusing

### ISSUE THREAD

**Issue by MicroJoe** [Michael-F-Bryan/gcode-rs#23]
For most of Gcode commands, the number after the comma is not used after I checked the spec.

I read in other issues that you have chosen f32 by simplicity, but it is kind of weird to compare on a f32 for this field. Especially when you know how strange floats can behave, for example getting sometimes 2.99999999 instead of 3. This makes programmer have to check Gcode like this:

```rust
if line.number() < 2.5 and line.number() > 1.5 {
    ...
}
```

Floats are fine for coordinates when we can tolerate float approximations, but for exact values we should be cautious. It is know dangerous to compare floats like this:

```rust
if line.number() == 2.0 { 
    ...
}
```

I propose to convert `number()` to u8 and introduce `minor_number()` that is u8 too if you find this appropriate.

**Comment by Michael-F-Bryan** [comment]
Have you seen [`Gcode::major_number()`] and [`Gcode::minor_number()`]?

That said, I think you're right that `Gcode::number()` is unintuitive. It should really be deprecated/removed seeing as you almost never want to treat the `1.1` in `G1.1` as a float anyway... The underlying `number` field should be changed to `(u8, Option<u8>)` to avoid those sticky rounding errors.

[`Gcode::major_number()`]: https://docs.rs/gcode/0.3.0/gcode/struct.Gcode.html#method.major_number
[`Gcode::minor_number()`]: https://docs.rs/gcode/0.3.0/gcode/struct.Gcode.html#method.minor_number
