### ISSUE TITLE
Put getting started example on cargo page

### ISSUE THREAD

**Issue by MicroJoe** [Michael-F-Bryan/gcode-rs#29]
The [crates.io description page](https://crates.io/crates/gcode) only shows the text description of the package, but interested users do not see at first glance how this library can fulfill his/her needs.

![image](https://user-images.githubusercontent.com/989521/46127398-d3a7ac00-c230-11e8-9a0a-b21f0324fd52.png)

It would be nice if the same example as in the README was shown on the cargo page.

**Comment by Michael-F-Bryan** [comment]
I think this is the same as #22, i.e. when releasing `0.3.1` I didn't fill out the `Cargo.toml` metadata correctly.

I'm doing a fairly large rewrite in #28, so hopefully it'll be fixed when that is released.
