### ISSUE TITLE
Unparsing?

### ISSUE THREAD

**Issue by icefoxen** [Michael-F-Bryan/gcode-rs#30]
Hi there, I was considering writing a program that has to read, then manipulate and output gcode commands.  Would you possibly accept a PR that added the ability to take a list of `Gcode` struct's and simply write them as text to a `Write` object or such?

**Comment by Michael-F-Bryan** [comment]
If you're using the latest library version, you should already be able to use `write!()` and [the `Display` impl][1] to do this.

[1]: https://docs.rs/gcode/0.3.1/src/gcode/types.rs.html#123-138

**Comment by icefoxen** [comment]
Thanks, I missed that `Display` was implemented!
